import { Link } from "react-router-dom";
import { useLanguage } from "@/contexts/LanguageContext";
import Icon, { type IconName } from "@/components/Icon";

export default function Landing() {
  const { lang, setLang } = useLanguage(); const tx = (en: string, id: string) => lang === "id" ? id : en;
  const features: { icon: IconName; title: string; text: string; to: string }[] = [
    { icon: "diary", title: tx("Personal nutrition, in perspective", "Gizi pribadi, dalam perspektif"), text: tx("Record food intake and compare it with your saved macronutrient allocation.", "Catat asupan pangan dan bandingkan dengan alokasi makronutrien tersimpan."), to: "/dashboard" },
    { icon: "lab", title: tx("A separate space for each case", "Ruang terpisah untuk setiap kasus"), text: tx("Calculate adult energy and macronutrient estimates without changing your personal profile.", "Hitung estimasi energi dan makronutrien dewasa tanpa mengubah profil pribadi."), to: "/tools" },
    { icon: "book", title: tx("Every step, open to discussion", "Setiap langkah, terbuka untuk diskusi"), text: tx("Use worked examples and source references to support nutrition teaching and professional review.", "Gunakan contoh hitung dan referensi untuk pembelajaran gizi dan tinjauan profesional."), to: "/references" },
  ];
  return <div className="public-site"><header className="public-nav"><Link className="brand" to="/"><span className="brand-mark">C<span>+</span></span><span>CalNut<small>{tx("NUTRITION, WITH UNDERSTANDING", "GIZI, DENGAN PEMAHAMAN")}</small></span></Link><nav aria-label="Public navigation"><Link to="/tools">{tx("Calculator", "Kalkulator")}</Link><Link to="/references">{tx("Sources", "Sumber")}</Link></nav><div className="topbar-actions"><select aria-label="Language" value={lang === "id" ? "id" : "en"} onChange={(event) => setLang(event.target.value as "id" | "en")}><option value="id">ID</option><option value="en">EN</option></select><Link className="btn-secondary" to="/login">{tx("Sign in", "Masuk")}</Link></div></header>
    <main><section className="public-hero"><div className="hero-copy"><p className="eyebrow">{tx("FOR NUTRITION PRACTICE & LEARNING", "UNTUK PRAKTIK & PEMBELAJARAN GIZI")}</p><h1>{tx("Good nutrition starts with", "Gizi yang baik dimulai dari")} <em>{tx("clear understanding.", "pemahaman yang jelas.")}</em></h1><p>{tx("One workspace for personal tracking, adult case calculations, and the conversations that turn numbers into informed decisions.", "Satu ruang kerja untuk pencatatan pribadi, perhitungan kasus dewasa, dan diskusi yang mengubah angka menjadi keputusan yang dipahami.")}</p><div className="planner-actions"><Link className="btn-primary" to="/register">{tx("Create your workspace", "Buat ruang kerja Anda")}<Icon name="arrow" size={17} /></Link><Link className="btn-secondary" to="/tools">{tx("Try the calculator", "Coba kalkulator")}</Link></div><p className="hero-audience">{tx("Students · Nutritionists · Lecturers · Clinical teams", "Mahasiswa · Nutrisionis · Dosen · Tim klinis")}</p></div>
      <div className="hero-example"><div className="panel-heading"><span className="eyebrow">{tx("A WORKED EXAMPLE", "CONTOH PERHITUNGAN")}</span><span className="pill">2,000 kcal</span></div><h2>{tx("Set two. Balance three.", "Atur dua. Seimbangkan tiga.")}</h2><p className="muted">{tx("Carbohydrate adapts to your protein and fat inputs.", "Karbohidrat menyesuaikan input protein dan lemak.")}</p><div className="hero-macros"><div><span>Protein</span><strong>25<small>%</small></strong><p>125 g</p></div><div><span>{tx("Fat", "Lemak")}</span><strong>20<small>%</small></strong><p>44.4 g</p></div><div className="hero-computed"><span>{tx("Carbohydrate", "Karbohidrat")}</span><strong>55<small>%</small></strong><p>275 g · {tx("automatic", "otomatis")}</p></div></div><div className="macro-stack"><span style={{ width: "55%", background: "#14857e" }} /><span style={{ width: "25%", background: "#5165c6" }} /><span style={{ width: "20%", background: "#c78c31" }} /></div><div className="hero-equation"><Icon name="check" size={16} />100 − 25 − 20 = 55% {tx("carbohydrate", "karbohidrat")}</div><p className="small-text muted">{tx("Illustrative allocation, not a universal dietary recommendation.", "Contoh alokasi, bukan rekomendasi diet universal.")}</p></div>
    </section><section className="public-features">{features.map((feature) => <Link key={feature.to} to={feature.to} className="public-feature"><span className="feature-icon"><Icon name={feature.icon} size={23} /></span><h2>{feature.title}</h2><p>{feature.text}</p><Icon name="arrow" size={18} /></Link>)}</section>
    <section className="public-trust"><div><p className="eyebrow">{tx("TRANSPARENT BY DESIGN", "TRANSPARAN SEJAK AWAL")}</p><h2>{tx("Know what the numbers can—and cannot—tell you.", "Pahami arti dan batasan setiap angka.")}</h2></div><p>{tx("CalNut shows its calculation methods and data limitations. Estimates support professional judgment; they do not establish diagnoses. Imported food records require source verification.", "CalNut menampilkan metode perhitungan dan batasan data. Estimasi mendukung pertimbangan profesional, bukan menetapkan diagnosis. Data pangan impor memerlukan verifikasi sumber.")} <Link to="/references">{tx("Read sources and methods", "Baca sumber dan metode")} →</Link></p></section></main><footer className="public-footer"><span>© {new Date().getFullYear()} CalNut</span><span>{tx("Built for nutrition practice and learning in Indonesia.", "Untuk praktik dan pembelajaran gizi di Indonesia.")}</span></footer>
  </div>;
}
