import { Link } from "react-router-dom";

export default function References() {
  return <main className="max-w-3xl mx-auto p-6 space-y-6">
    <Link to="/" className="font-bold text-primary">CalNut</Link>
    <h1 className="text-3xl font-bold">Sources, methods & data quality / Sumber dan metode</h1>
    <p>Reference review: 8 September 2026. Sources are dated individually; CalNut does not automatically update published guidance or certify imported food records.</p>
    <section className="space-y-2"><h2 className="text-xl font-bold">Indonesian reference intakes (AKG)</h2><p>Adult reference values follow Permenkes 28/2019, Annex I, tables 1 and 3. The official registry lists it as in force. Comparisons use age and sex groups, not a personal prescription. Pregnancy, lactation, children, and disease-specific requirements are not implemented. At age 80 the app uses the 80+ row; the source labels overlap.</p><a className="underline" href="https://jdih.kemkes.go.id/storage/documents/pdfs/2019permenkes028.pdf">Kementerian Kesehatan: AKG tables</a></section>
    <section className="space-y-2"><h2 className="text-xl font-bold">TDEE and macronutrients</h2><p>Mifflin–St Jeor estimates resting energy expenditure (REE), not measured basal metabolism. CalNut multiplies it by the selected activity factor (1.2–1.9) to estimate TDEE. These activity multipliers are application assumptions, not part of the original equation. The original study involved healthy adults aged 19–78; no TDEE target is generated outside this age range.</p><a className="underline" href="https://pubmed.ncbi.nlm.nih.gov/2305711/">Original Mifflin–St Jeor study</a><p>Energy allocation = TDEE × percentage ÷ 100. Divide allocated kcal by 4 for carbohydrate and protein, or by 9 for fat. Custom targets must total 100%; they do not replace AKG population reference values.</p></section>
    <section className="space-y-2"><h2 className="text-xl font-bold">Dietary guidance</h2><p>The original 45–65% carbohydrate, 20–30% protein, and 10–20% fat hints were project-specific examples, not a universal guideline. Current WHO guidance emphasizes food quality and suggests adults limit total fat to 30% of energy or less to help prevent unhealthy weight gain. Individual allocations require context.</p><a className="underline" href="https://www.who.int/news-room/fact-sheets/detail/healthy-diet">WHO: Healthy diet</a></section>
    <section className="space-y-2"><h2 className="text-xl font-bold">BMI</h2><p>The existing gauge uses Asia-Pacific adult bands: below 18.5, 18.5–22.9, 23–24.9, 25–29.9, and 30 or more. These are not universal WHO cutoffs. WHO's 2004 Asian consultation retained international classifications and identified additional risk action points including 23 and 27.5. BMI is a screening measure, not a diagnosis; adult categories should not be used for children or pregnancy.</p><a className="underline" href="https://pubmed.ncbi.nlm.nih.gov/14726171/">WHO Expert Consultation on Asian BMI</a></section>
    <section className="space-y-2"><h2 className="text-xl font-bold">Food records require verification</h2><p>The Ministry lists a revised TKPI publication from 2020. The supplied tkpi2020_data.json contains 1,900 records, but its transcription has not been validated against that publication. An audit found at least 312 records with water, protein, or ash above 100 g per 100 g. Passing automated checks does not establish accuracy. The legacy built-in list and administrator-added foods also require source review.</p><p>Imported rows with impossible values or missing tracked nutrients are excluded from new search calculations. Missing values must not be interpreted as measured zero. Existing diary records retain their original values and should be reviewed. Use weighed edible portions; household-unit weights are approximate.</p><a className="underline" href="https://repository.kemkes.go.id/book/668">Kementerian Kesehatan: TKPI 2020 publication</a></section>
  </main>;
}
